services:
  hotel-japones:
    build: .
    restart: unless-stopped
    container_name: hotel-japones
    networks:
        - web_proxy_network
networks:
    web_proxy_network:
        external: true
